In [1]:
import pandas as pd
import numpy as np

In [36]:
def gauss_elimination(A, B):
    if A.shape[0] != A.shape[1]:
        raise ValueError("Matrix A must be square")
    if A.shape[0] != B.shape[0]:
        raise ValueError("Matrix A and B must have the same number of rows")
    
    #create augmented matrix
    augmented = np.concatenate((A,B), axis=1, dtype=np.float64)

    n = A.shape[0]
    for i in range(n):
        pivot = augmented[i, i]
        if pivot == 0:
            raise ValueError("Pivot element is zero")
        for j in range(i+1, n):
            scaling_factor = augmented[j, i] / pivot
            # A[j, :] -= scaling_factor * A[i, :]
            augmented[j, :] -= scaling_factor * augmented[i, :]

        print(augmented)

In [43]:
A = np.array([[2,1,3],[15,2,0],[1,3,1]])
B = np.array([10, 5, 3]).reshape(-1,1)
# gauss_elimination(A,B)
A[[0, 1]] = A[[1, 0]]
A

array([[15,  2,  0],
       [ 2,  1,  3],
       [ 1,  3,  1]])

In [57]:
def gauss_elimination_with_partial_pivot(A, B):

    A = A.astype(np.float64)
    B = B.astype(np.float64)

    if A.shape[0] != A.shape[1]:
        raise ValueError("Matrix A must be square")

    if A.shape[0] != B.shape[0]:
        raise ValueError("Matrix A and B must have the same number of rows")
    
    augmented = np.hstack((A, B))

    n = A.shape[0]

    for i in range(n):

        max_row = np.argmax(np.abs(augmented[i:, i])) + i
        if augmented[max_row, i] == 0:
            raise ValueError("Matrix is Singular")
        if max_row != i:
            augmented[[i, max_row]] = augmented[[max_row, i]]

        for j in range(i+1, n):
            scaling_factor = augmented[j, i] / augmented[i, i]
            augmented[j, :] -= scaling_factor * augmented[i, :]
        print(augmented)

    x = np.zeros((n, 1))
    for i in range(n-1, -1, -1):
        x[i] = (augmented[i, -1] - np.dot(augmented[i, i+1:n], x[i+1:n].flatten())) / augmented[i, i]

    return x

In [58]:
A = np.array([[50,47,48],[10,27,79],[17,398,12]])
B = np.array([77, 23, 33]).reshape(-1,1)
gauss_elimination_with_partial_pivot(A,B)

[[ 50.    47.    48.    77.  ]
 [  0.    17.6   69.4    7.6 ]
 [  0.   382.02  -4.32   6.82]]
[[ 50.          47.          48.          77.        ]
 [  0.         382.02        -4.32         6.82      ]
 [  0.           0.          69.59902623   7.28579656]]
[[ 50.          47.          48.          77.        ]
 [  0.         382.02        -4.32         6.82      ]
 [  0.           0.          69.59902623   7.28579656]]


array([[1.42161077],
       [0.01903625],
       [0.10468245]])